
apiVersion: batch/v1
kind: CronJob
metadata:
  name: gold-price-notify
spec:
  schedule: "*/2 * * * *"   # every 2 minutes
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: gold-app
            image: harshalpantawane/gold-app:latest
            imagePullPolicy: Always
            env:
            - name: GOLD_API_KEY
              valueFrom:
                secretKeyRef:
                  name: gold-secret
                  key: GOLD_API_KEY
                  
            - name: SNS_TOPIC_ARN
              value: "arn:aws:sns:us-east-1:890871562773:notify"

            - name: AWS_REGION
              value: "us-east-1"
                
          restartPolicy: OnFailure