apiVersion: batch/v1
kind: Cronjob
metadata:
  name: gold-price-notify
spec:
  schedule: "*/2 * * * *"       # every 2 minutes
  jobTemplate:
   spec:
     template:
       spec:
         containers:
         - name: gold-app
           image: harshalpantawane/gold-app:latest
           envFrom:
           - secretRef:
              name: gold-secret
         restartPolicy: onFailure

