apiVersion: v1
kind: Secret
metadata:
  name: gold-secret
type: Opaque
stringData:
  GOLD_API_KEY: "goldapi-eqr6800smna0c40m-io"
  EMAIL_SENDER: "hmpantawane2214@gmail.com" 
  EMAIL_RECEIVER: "xabc47441@gmail.com"
  EMAIL_PASSWORD: "Harshal@14"   
    